version: '3.2'

networks:
  algorithms:
    driver: bridge

services:

  nginx_algorithms1:
    container_name: algorithms_nginx_backend1
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8905:80
    links:
      - 'php_fpm_algorithms'
    networks:
      - algorithms

  php_fpm_algorithms:
    container_name: algorithms_php_fpm
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ../:/application
      - ../docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      - algorithms