version: '3.2'

networks:
  algorithms:
    driver: bridge

services:

  nginx_alg:
    container_name: nginx_alg
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8905:80
    links:
      - 'phpfpm_alg'
    networks:
      - algorithms

  phpfpm_alg:
    container_name: phpfpm_alg
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ../:/application
      - ../docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      - algorithms

  pgsql_alg:
    container_name: pgsql_alg
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=algorithms_user
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=algorithms_db
    volumes:
      - ../docker/postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - 54320:5432
    networks:
      - algorithms

  pgsql_alg_test:
    container_name: pgsql_alg_test
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=algorithms_user
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=algorithms_db_test
    ports:
      - 54330:5432
    networks:
      - algorithms