#!make
init:
	docker-compose exec phpfpm_alg mkdir -p logs
	docker-compose exec phpfpm_alg chmod -R 777 logs/

refresh:
	docker-compose exec phpfpm_alg chmod -R 777 logs/

update:
	docker-compose exec phpfpm_alg chmod -R 777 logs/
